apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlite-pv
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: dev-dt
    name: sqlite-pvc
  hostPath:
    type: DirectoryOrCreate
    path: "/data-q"
