apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dt-sqlite
  name: dt-sqlite
  namespace: dev-dt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dt-sqlite
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dt-sqlite
    spec:
      containers:
      - image: mysql:8.2
        name: mysql
        resources: {}
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: dtconfig
              key: mysql_db
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-password
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: sqlite-pvc
      volumes:
      - name: sqlite-pvc
        persistentVolumeClaim:
          claimName: sqlite-pvc
status: {}