apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dt-sqlite
  name: dt-sqlite
  namespace: dev-dt
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: dt-sqlite
  type: ClusterIP
status:
  loadBalancer: {}
