apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlite-pv
  namespace: dev-dt
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/sqlite/example/db.sqlite3"
    type: File
